services:
  server:
    container_name: emprestaii-api
    build:
      context: .
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=emprestaii.settings
      - POSTGRES_PORT=5432
      - POSTGRES_USER=teste
      - POSTGRES_PASSWORD=teste
      - POSTGRES_DB=teste
    depends_on:
      - db
    volumes:
      - ./emprestaii:/project/emprestaii
    ports:
      - "8000:8000"
    entrypoint:
      - /entrypoint.sh

  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=teste
      - POSTGRES_PASSWORD=teste
      - POSTGRES_DB=teste
    ports:
      - "5432:5432"
